### ISSUE TITLE
Chrome version 80

### ISSUE THREAD

**Issue by donkw** [zellyn/kooky#12]
Looks like doesn't support Chrome version 80?

**Comment by srlehn** [comment]
https://stackoverflow.com/a/60423699

**Comment by donkw** [comment]
> https://stackoverflow.com/a/60423699

Thank you, this is useful.

**Comment by srlehn** [comment]
Please reopen this until kooky can handle the new cookies.

I would like to implement it based on the stackoverflow post but that won't be any time soon.

**Comment by donkw** [comment]
> Please reopen this until kooky can handle the new cookies.
> 
> I would like to implement it based on the stackoverflow post but that won't be any time soon.

done.

**Comment by n0v3xx** [comment]
Any progress?

**Comment by zellyn** [comment]
@n0v3xx, any progress?

Just (mostly) kidding. The http://unmaintained.tech/ badge is real. I'll probably take a look at this, eventually. But with quarantine, and an injured wife, and promo season at work, etc., etc., it might be a while. PRs welcome! This is _your_ library!

**Comment by srlehn** [comment]
issue title should include that this is windows-only
