### ISSUE TITLE
Safari cookies no longer readable after upgrade to Mojave

### ISSUE THREAD

**Issue by DukeyToo** [zellyn/kooky#7]
OSX Mojave protects the Safari cookie folder via [Full Disk Access](https://macpaw.com/how-to/full-disk-access-mojave) feature. This causes error "operation not permitted" when accessing the file.

In my usage, it can be worked around by granting Full Disk Access to my terminal app, which seems to give anything I call from the terminal access as well.

**Comment by zellyn** [comment]
Oops. Meant to comment and close. Makes sense it would need full disk access, though. ¯\\\_(ツ)\_/¯
